project_name: enduro

before:
  hooks:
  - apk add --no-cache make
  - make generate ui-gen

changelog:
  skip: true

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  flags:
  - -trimpath
  ldflags:
  - -X "main.buildTime={{.Date}}"
  - -X "main.gitCommit={{.Commit}}"
  - -X "main.version={{.Version}}"

archives:
- wrap_in_directory: true
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    amd64: 64bit
  files:
  - LICENSE
  - README.md
  - enduro.toml

checksum:
  name_template: checksums.txt
  algorithm: sha256
