log:
  level: "info"

services:
  frontend:
    rpc:
      port: 7400
      bindOnLocalHost: false
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "127.0.0.1:7401"
    pprof:
      port: 7402
  matching:
    rpc:
      port: 7410
      bindOnLocalHost: false
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "127.0.0.1:7411"
    pprof:
      port: 7412
  history:
    rpc:
      port: 7420
      bindOnLocalHost: false
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "127.0.0.1:7421"
    pprof:
      port: 7422
  worker:
    rpc:
      port: 7430
      bindOnLocalHost: false
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "127.0.0.1:7431"
    pprof:
      port: 7432

ringpop:
  name: "cadence"
  bootstrapMode: "hosts"
  bootstrapHosts:
    - "cadence:7400"
    - "cadence:7410"
    - "cadence:7420"
    - "cadence:7430"
  maxJoinDuration: "10s"

clusterMetadata:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "127.0.0.1:7400"

publicClient:
  hostPort: "localhost:7400"

persistence:
  defaultStore: "default"
  visibilityStore: "visibility"
  numHistoryShards: 4
  datastores:
    default:
      sql:
        driverName: "mysql"
        databaseName: "cadence"
        connectAddr: "mysql:3306"
        connectProtocol: "tcp"
        user: "enduro"
        password: "enduro123"
    visibility:
      sql:
        driverName: "mysql"
        databaseName: "cadence_visibility"
        connectAddr: "mysql:3306"
        connectProtocol: "tcp"
        user: "enduro"
        password: "enduro123"

archival:
  history:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    status: "disabled"
    enableRead: false

domainDefaults:
  archival:
    history:
      status: "enabled"
      URI: "file:///tmp/cadence_archival_history/development"
    visibility:
      status: "disabled"
