on:
  push:
    tags:
      - 'v*'
name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    #needs: [ test ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install UI dependencies
      run: yarn --cwd ui install
    - name: Build UI
      run: yarn --cwd ui build
    - name: GoReleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.QUBOT_GITHUB_TOKEN }}
      with:
        args: release
      if: success()
    - name: Set RELEASE_VERSION
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Send notification to Jenkins
      uses: swinton/httpie.action@master
      env:
        JENKINS_TOKEN: "${{ secrets.JENKINS_TOKEN }}"
        RELEASE_VERSION: "${{ env.RELEASE_VERSION }}"
      with:
        args: >-
          https://jenkins-ci.archivematica.org/job/am-packbuild/job/rpm-jenkinsci/buildWithParameters
            token==$JENKINS_TOKEN
            PACKAGE==enduro
            VERSION==$RELEASE_VERSION
            RELEASE==1
            PACKBUILD_BRANCH==dev/enduro-package
            REPOSITORY==nha
      if: success()
